### ISSUE TITLE
Doesn't work out of the box

### ISSUE THREAD

**Issue by c4s4** [yigitpirildak/SimpleJNIDemo#1]
If you clone the project and type `make run_temperaturesampler`, this won't work as you must set *JAVA_HOME*. It could run out of the box setting *JAVA_HOME* with following line:

```
export JAVA_HOME=$(shell dirname `which java`)/..
```

**Comment by yigitpirildak** [comment]
This is actually not working for me, 'which java' points to the binary executable which resides under /usr/bin. It's not a direct symlink to jvm folder for me in Ubuntu 18.
Here's the symlink order for me : /usr/bin/java -> /etc/alternatives/java -> /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java

Maybe this would work if you had a single java version installed on your machine.
My assumption was that JAVA_HOME variable would be modified before running the script as described in project description.
What output are you getting from that shell command?

**Comment by c4s4** [comment]
This should work, following symlinks:

```
export JAVA_HOME=$(shell readlink -f $(shell dirname `which java`/..))
```

**Comment by yigitpirildak** [comment]
Unfortunately, it also doesn't work.
That command resolves the symlinks but still points to the java executable, not the root of jvm folder. We could get rid of the latest part of the path but that would be relying on the folder structure.

Following command seems to work for me which grabs the path to currently selected jvm version although this also relies on folder structure:
`export JAVA_HOME= $(shell update-alternatives --display java | grep -e "link currently points to" | sed 's/\  link currently points to //' | sed 's/\/jre\/bin\/java//g')`

This path tends to change based on different jdks (For example, if you download azul's jdk package, jre related binaries are directly included under /bin rather than /jre/bin)

So, even though it works for me at the moment (which might also work for you), it's still unreliable to grab the path like this, IMO.
